// <auto-generated />
using System;
using EfScmDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfScmDataAccess.Migrations
{
    [DbContext(typeof(EfScmContext))]
    partial class EfScmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("EfScmDataAccess.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<int>("OrderThreshold");

                    b.Property<int?>("PartTypeId");

                    b.HasKey("Id");

                    b.HasIndex("PartTypeId");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("EfScmDataAccess.PartType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("EfScmDataAccess.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<int?>("PartId");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("EfScmDataAccess.InventoryItem", b =>
                {
                    b.HasOne("EfScmDataAccess.PartType", "PartType")
                        .WithMany()
                        .HasForeignKey("PartTypeId");
                });

            modelBuilder.Entity("EfScmDataAccess.Supplier", b =>
                {
                    b.HasOne("EfScmDataAccess.PartType", "Part")
                        .WithMany()
                        .HasForeignKey("PartId");
                });
#pragma warning restore 612, 618
        }
    }
}
